//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digitude.Adfs.CustomImagesThemeGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Digitude.Adfs.CustomImagesThemeGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * {
        ///	margin:0px;
        ///	padding:0px;
        ///}
        ///html, body
        ///{
        ///    height:100%;
        ///    width:100%;
        ///    background-color:#ffffff;
        ///    color:#000000;
        ///    font-weight:normal;
        ///    font-family:&quot;Segoe UI&quot; , &quot;Segoe&quot; , &quot;SegoeUI-Regular-final&quot;, Tahoma, Helvetica, Arial, sans-serif;
        ///    min-width:500px;
        ///    -ms-overflow-style:-ms-autohiding-scrollbar;
        ///}
        ///
        ///body
        ///{
        ///    font-size:0.9em;
        ///}
        ///
        ///#noScript { margin:16px; color:Black; }
        ///
        ///:lang(en-GB){quotes:&apos;\2018&apos; &apos;\2019&apos; &apos;\201C&apos; &apos;\201D&apos;;}
        ///:lang(zh){font-family:微软雅黑;}
        ///
        ///@-m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string customstyle {
            get {
                return ResourceManager.GetString("customstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon mockup_YCw_icon {
            get {
                object obj = ResourceManager.GetObject("mockup_YCw_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) Microsoft Corporation.  All rights reserved.
        ///
        ///// This file contains several workarounds on inconsistent browser behaviors that administrators may customize.
        ///&quot;use strict&quot;;
        ///
        ///var language = document.documentElement.lang;
        ///var languageKey = &apos;en&apos;;
        ///
        ///if (language.lastIndexOf(&apos;nl&apos;, 0) === 0) {
        ///    languageKey = &apos;nl&apos;;
        ///}
        ///else if (language.lastIndexOf(&apos;fr&apos;, 0) === 0) {
        ///    languageKey = &apos;fr&apos;;
        ///}
        ///
        ///// iPhone email friendly keyboard does not include &quot;\&quot; key, use regular keyboard instead.
        ///// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string onload {
            get {
                return ResourceManager.GetString("onload", resourceCulture);
            }
        }
    }
}
